-- ==========================================
-- Wannasingh Blog - Oracle Database Schema
-- Compatible with Oracle Database 19c / 21c / 23c
-- ==========================================

-- Drop tables if they exist (for easy teardown/rebuild)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE messages CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE notifications CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE likes CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE comments CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE posts CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE statuses CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE categories CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 1. Users Table
-- Uses VARCHAR2(36) for UUID compatibility with legacy Supabase user IDs
CREATE TABLE users (
    id           VARCHAR2(36) PRIMARY KEY,
    username     VARCHAR2(50) UNIQUE NOT NULL,
    name         VARCHAR2(100) NOT NULL,
    password     VARCHAR2(255) NOT NULL,
    role         VARCHAR2(20) DEFAULT 'user' NOT NULL,
    profile_pic  VARCHAR2(1000),
    bio          VARCHAR2(1000),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_users_role CHECK (role IN ('user', 'admin'))
);

-- 2. Categories Table
CREATE TABLE categories (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR2(100) UNIQUE NOT NULL
);

-- 3. Statuses Table
CREATE TABLE statuses (
    id           NUMBER PRIMARY KEY,
    status       VARCHAR2(50) UNIQUE NOT NULL
);

-- Insert standard post statuses
INSERT INTO statuses (id, status) VALUES (1, 'Draft');
INSERT INTO statuses (id, status) VALUES (2, 'Published');
COMMIT;

-- 4. Posts Table
-- PostgreSQL TEXT is converted to Oracle CLOB
-- PostgreSQL TIMESTAMPTZ is converted to Oracle TIMESTAMP WITH TIME ZONE
CREATE TABLE posts (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR2(255) NOT NULL,
    image        VARCHAR2(1000),
    category_id  NUMBER,
    description  VARCHAR2(4000),
    content      CLOB NOT NULL,
    status_id    NUMBER DEFAULT 1 NOT NULL,
    user_id      VARCHAR2(36) NOT NULL,
    date         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_posts_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_posts_status FOREIGN KEY (status_id) REFERENCES statuses(id),
    CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 5. Comments Table
CREATE TABLE comments (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id      NUMBER NOT NULL,
    user_id      VARCHAR2(36) NOT NULL,
    comment_text VARCHAR2(1000) NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 6. Likes Table
CREATE TABLE likes (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id      NUMBER NOT NULL,
    user_id      VARCHAR2(36) NOT NULL,
    CONSTRAINT uq_likes_post_user UNIQUE (post_id, user_id),
    CONSTRAINT fk_likes_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_likes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 7. Notifications Table
-- Oracle lacks native SQL BOOLEAN in older versions. We use CHAR(1) check ('Y'/'N') for compatibility.
CREATE TABLE notifications (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      VARCHAR2(36) NOT NULL, -- Liked/Commented by user_id
    post_id      NUMBER,
    type         VARCHAR2(50) NOT NULL,
    content      VARCHAR2(500),
    is_read      CHAR(1) DEFAULT 'N' NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_notifications_read CHECK (is_read IN ('Y', 'N')),
    CONSTRAINT fk_notifications_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 8. Messages Table
CREATE TABLE messages (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id    VARCHAR2(36) NOT NULL,
    receiver_id  VARCHAR2(36) NOT NULL,
    message      VARCHAR2(4000) NOT NULL,
    is_read      CHAR(1) DEFAULT 'N' NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_messages_read CHECK (is_read IN ('Y', 'N')),
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_receiver FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create indexes for performance on foreign keys and commonly searched fields
CREATE INDEX idx_posts_user ON posts(user_id);
CREATE INDEX idx_posts_category ON posts(category_id);
CREATE INDEX idx_comments_post ON comments(post_id);
CREATE INDEX idx_likes_post ON likes(post_id);
CREATE INDEX idx_messages_conversation ON messages(sender_id, receiver_id);
CREATE INDEX idx_notifications_unread ON notifications(is_read);
